M48
; DRILL file {KiCad 9.0.4} date 2026-02-27T16:14:02-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-27T16:14:02-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X120.745Y-99.71
X120.745Y-105.49
T2
X54.65Y-92.3
X54.65Y-112.3
X124.65Y-92.3
X124.65Y-112.3
M30
